[google_credentials]
type = "service_account"
project_id = "ump-dream"
private_key_id = "fe4ef59b2d426f2425238ba9ca84b7dc1771b05e"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDpPu9MvJtqsvYV
MXIB4srnlzBvKJfdgjYQQRVbDb2t8TaKUEfJW7KmtJGH/ZERmm69EnsUIPnI/4pI
CEgD39c65SmxguvTr4FH3CFlM+7ZY1lzmTqDcW9klEREHFXigxVdutWBNw5YwtiU
1ncJCOEGwSmOO3rDay2jSvIZ3fCzgaXPCPf6mQxG2jneMco3cdp5RIMhwMv0vSi1
pEiN7YTvQtnXyyo7fTmAxWQE+63zZzrw1CzMOMXe/bDRUJ8F7SOLwdaVXSR7eQ7r
J3UIyBNrQhB3H3EppVjmbQvmx7R+QGxUr2oLU9lPMuuNWLSyi9+aErwiUxNaQ11L
kDVl62H5AgMBAAECggEAJqMogGFw7FqjZYzYiiPvwS/cE9nZWFX4zzX8y+XJkT4X
Lw/P6HTicfeQ8QJJzOz0YaklTscMoaVlGnwWs9+ZV3X9M1zQ5HLa+1Slio5xBz1M
JNhR51K75WEjMtYvyvM0b5+ivQIqA/2Y44ToWIyKPDR0xg0nz6XaPEXOt4a6l/11
x1Q4iNfYc39mWQ3J96fh34qwPpk+EK+QOPB70C0wfZ8iydFOt/cfilmUD3PO9G2u
biBNIYRTwnW2ZxlKPLSRz7vBtoz6b8QiV4nlYDMrW+X+mA1WQZOljh/BmcBc3+CU
p5wd06DsOUKhJjhG1tBjRNHlLAfj4+lGDbbhlDHo5QKBgQD6Oql8nwAfmzdEDpeg
Gjs7GWKG21smCx429LE1ng2zyPmjAt31MDjxW9MfUrc8MaQ5dmuIAEE9Tp/8m9Vm
T+8S8rqtxXPC7HncQJTNj43kXp2Bvcf0n9WMOr/hWdQMaKaBx665NDIwcrbwwk9w
8FGZ281IGbxkvckgHH38MolaxQKBgQDuoAEXPl8meI1VkvLtqPCHFohvqUoqpq13
aPzpvMfENUZJUHn0a4iVbmprxOe+g1J+Ly+pDS5Mp+N8yVc6qxE3z8Bviqrx8cmO
A7uEGBQwDMsr4LGojdiprRP6vv3FEkiFJ4WYGqfGA8SCvY+7uW02ChR515MC3tSK
9zitTKZtpQKBgQDye25KiXoBJtSDavCcAU9skcjcjizhzNxWvQAMyUDV++eNg/W6
6CQGH8mTDQDrn99Yn9zMShLuaga3L/u3zbYLUpR8WF85gRcFzL9mA7qoltdjJpli
AJFb9oKCyh2meLMCCJLUfjQ0prWI0YNSGk+5HTrsp6Pcq9z+9R1RC1f3UQKBgGMD
7a/xZ5YVC8Boe3j2UugbB34d5vKPuwcDf36VoObfnEyrog8z17b53Brf17GL2F0X
w1UIbR/Nwm1zNkjX1wsrn5QpHAnM5G+TSOnk++t8Q4nvcIiaYz703Id9XNu7XHA0
GBEnblqSEaaWdd/Vb2WvBRQRyaS1RchsEQ6H8b8pAoGBALZHrLTBYpjHDO2qhJS+
nqX9qFeQedbxd1JOwnkl0KAn0jcxTy92FIfgpun2P2W0/OmnP0zsU+Di4hrW+DAi
DI+0CLu1TRULkm9k5novPFMOXzNN7/qF1wPxP4C9rT2uQhSvYm6W3pEwgGbooUij
oXNWQIC/kT7MvBsUTOHrHHQc
-----END PRIVATE KEY-----
"""
client_email = "ump-dream@ump-dream.iam.gserviceaccount.com"
client_id = "108261381569766790403"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ump-dream%40ump-dream.iam.gserviceaccount.com"

# Cấu hình Google Drive
drive_folder_id = "https://drive.google.com/drive/folders/12A6xIR0M6tyou556VCcCqvBDhUcgHKC6?usp=sharing"  # ID folder images
spreadsheet_id = "1Gd4ZEMhKvzxpUhLL4C8lmSzI2RAeFgr8QPBu0efn6IA"   # ID Google Sheet